### ISSUE TITLE
Not building the firmware

### ISSUE THREAD

**Issue by gennionamics** [jnz/stm32boy#1]
Hello,
I am trying to build the firmware and I followed all the steps in the README file. However when I hit the "make" I get the following:

![image](https://github.com/user-attachments/assets/75bab17e-741a-4a34-ac2a-09b97aeac97a)

**Comment by JohnZ03** [comment]
Try manually create a folder "build" under the project dir, then `make`.

**Comment by gennionamics** [comment]
Thanks, it worked.
I would suggest some minor changes to the Makefile to automatically manage the "build" folder. I tried to create a branch but didn't have the permission to push

**Comment by jnz** [comment]
Thanks, good point. I've added a dummy file with the build directory to the repository.
