### ISSUE TITLE
How is the portability?

### ISSUE THREAD

**Issue by JohnZ03** [jnz/stm32boy#3]
Thanks for your time in advance. I do have a question regarding the portability of this implementation.

Would it be easier to port this project onto a different STM32 chip, or you would suggest look into Peanut-GB start from there?

I noticed that the BSP lib for stm32f429i_discovery board is being used, could you please give a brief info on the IOs of the chip being used here?

**Comment by jnz** [comment]
I'd consider this repository a wrapper around Peanut-GB and the F429-Discovery BSP.
The Discover Board has a manual: [LINK](https://www.st.com/resource/en/user_manual/um1670-discovery-kit-with-stm32f429zi-mcu-stmicroelectronics.pdf)
